-- Source: https://www.freeformatter.com/html-entities.html
return {
	-- XML
	["quot"] = '"', -- &#39; Apostrophe
	["amp"]  = "&", -- &#38; Ampersand
	["apos"] = "'", -- &#39; Apostrophe
	["lt"]   = "<", -- &#60; Less-than
	["gt"]   = ">", -- &#62; Greater than

	--
	-- HTML
	--

	-- ISO-8859-1 Characters
	["Agrave"] = "À", -- &#192; Capital a with grave accent
	["Aacute"] = "Á", -- &#193; Capital a with acute accent
	["Acirc"]  = "Â", -- &#194; Capital a with circumflex accent
	["Atilde"] = "Ã", -- &#195; Capital a with tilde
	["Auml"]   = "Ä", -- &#196; Capital a with umlaut
	["Aring"]  = "Å", -- &#197; Capital a with ring
	["AElig"]  = "Æ", -- &#198; Capital ae
	["Ccedil"] = "Ç", -- &#199; Capital c with cedilla
	["Egrave"] = "È", -- &#200; Capital e with grave accent
	["Eacute"] = "É", -- &#201; Capital e with acute accent
	["Ecirc"]  = "Ê", -- &#202; Capital e with circumflex accent
	["Euml"]   = "Ë", -- &#203; Capital e with umlaut
	["Igrave"] = "Ì", -- &#204; Capital i with grave accent
	["Iacute"] = "Í", -- &#205; Capital i with accute accent
	["Icirc"]  = "Î", -- &#206; Capital i with circumflex accent
	["Iuml"]   = "Ï", -- &#207; Capital i with umlaut
	["ETH"]    = "Ð", -- &#208; Capital eth (Icelandic)
	["Ntilde"] = "Ñ", -- &#209; Capital n with tilde
	["Ograve"] = "Ò", -- &#210; Capital o with grave accent
	["Oacute"] = "Ó", -- &#211; Capital o with accute accent
	["Ocirc"]  = "Ô", -- &#212; Capital o with circumflex accent
	["Otilde"] = "Õ", -- &#213; Capital o with tilde
	["Ouml"]   = "Ö", -- &#214; Capital o with umlaut
	["Oslash"] = "Ø", -- &#216; Capital o with slash
	["Ugrave"] = "Ù", -- &#217; Capital u with grave accent
	["Uacute"] = "Ú", -- &#218; Capital u with acute accent
	["Ucirc"]  = "Û", -- &#219; Capital u with circumflex accent
	["Uuml"]   = "Ü", -- &#220; Capital u with umlaut
	["Yacute"] = "Ý", -- &#221; Capital y with acute accent
	["THORN"]  = "Þ", -- &#222; Capital thorn (Icelandic)
	["szlig"]  = "ß", -- &#223; Lowercase sharp s (German)
	["agrave"] = "à", -- &#224; Lowercase a with grave accent
	["aacute"] = "á", -- &#225; Lowercase a with acute accent
	["acirc"]  = "â", -- &#226; Lowercase a with circumflex accent
	["atilde"] = "ã", -- &#227; Lowercase a with tilde
	["auml"]   = "ä", -- &#228; Lowercase a with umlaut
	["aring"]  = "å", -- &#229; Lowercase a with ring
	["aelig"]  = "æ", -- &#230; Lowercase ae
	["ccedil"] = "ç", -- &#231; Lowercase c with cedilla
	["egrave"] = "è", -- &#232; Lowercase e with grave accent
	["eacute"] = "é", -- &#233; Lowercase e with acute accent
	["ecirc"]  = "ê", -- &#234; Lowercase e with circumflex accent
	["euml"]   = "ë", -- &#235; Lowercase e with umlaut
	["igrave"] = "ì", -- &#236; Lowercase i with grave accent
	["iacute"] = "í", -- &#237; Lowercase i with acute accent
	["icirc"]  = "î", -- &#238; Lowercase i with circumflex accent
	["iuml"]   = "ï", -- &#239; Lowercase i with umlaut
	["eth"]    = "ð", -- &#240; Lowercase eth (Icelandic)
	["ntilde"] = "ñ", -- &#241; Lowercase n with tilde
	["ograve"] = "ò", -- &#242; Lowercase o with grave accent
	["oacute"] = "ó", -- &#243; Lowercase o with acute accent
	["ocirc"]  = "ô", -- &#244; Lowercase o with circumflex accent
	["otilde"] = "õ", -- &#245; Lowercase o with tilde
	["ouml"]   = "ö", -- &#246; Lowercase o with umlaut
	["oslash"] = "ø", -- &#248; Lowercase o with slash
	["ugrave"] = "ù", -- &#249; Lowercase u with grave accent
	["uacute"] = "ú", -- &#250; Lowercase u with acute accent
	["ucirc"]  = "û", -- &#251; Lowercase u with circumflex accent
	["uuml"]   = "ü", -- &#252; Lowercase u with umlaut
	["yacute"] = "ý", -- &#253; Lowercase y with acute accent
	["thorn"]  = "þ", -- &#254; Lowercase thorn (Icelandic)
	["yuml"]   = "ÿ", -- &#255; Lowercase y with umlaut

	-- ISO-8859-1 Symbols
	["nbsp"]   = " ", -- &#160; Non-breaking space
	["iexcl"]  = "¡", -- &#161; Inverted exclamation mark
	["cent"]   = "¢", -- &#162; Cent
	["pound"]  = "£", -- &#163; Pound
	["curren"] = "¤", -- &#164; Currency
	["yen"]    = "¥", -- &#165; Yen
	["brvbar"] = "¦", -- &#166; Broken vertical bar
	["sect"]   = "§", -- &#167; Section
	["uml"]    = "¨", -- &#168; Spacing diaeresis
	["copy"]   = "©", -- &#169; Copyright
	["ordf"]   = "ª", -- &#170; Feminine ordinal indicator
	["laquo"]  = "«", -- &#171; Opening/Left angle quotation mark
	["not"]    = "¬", -- &#172; Negation
	["shy"]    = "­", -- &#173; Soft hyphen
	["reg"]    = "®", -- &#174; Registered trademark
	["macr"]   = "¯", -- &#175; Spacing macron
	["deg"]    = "°", -- &#176; Degree
	["plusmn"] = "±", -- &#177; Plus or minus
	["sup2"]   = "²", -- &#178; Superscript 2
	["sup3"]   = "³", -- &#179; Superscript 3
	["acute"]  = "´", -- &#180; Spacing acute
	["micro"]  = "µ", -- &#181; Micro
	["para"]   = "¶", -- &#182; Paragraph
	["cedil"]  = "¸", -- &#184; Spacing cedilla
	["sup1"]   = "¹", -- &#185; Superscript 1
	["ordm"]   = "º", -- &#186; Masculine ordinal indicator
	["raquo"]  = "»", -- &#187; Closing/Right angle quotation mark
	["frac14"] = "¼", -- &#188; Fraction 1/4
	["frac12"] = "½", -- &#189; Fraction 1/2
	["frac34"] = "¾", -- &#190; Fraction 3/4
	["iquest"] = "¿", -- &#191; Inverted question mark
	["times"]  = "×", -- &#215; Multiplication
	["divide"] = "÷", -- &#247; Divide

	-- Math Symbols
	["forall"] = "∀", -- &#8704; For all
	["part"]   = "∂", -- &#8706; Part
	["exist"]  = "∃", -- &#8707; Exist
	["empty"]  = "∅", -- &#8709; Empty
	["nabla"]  = "∇", -- &#8711; Nabla
	["isin"]   = "∈", -- &#8712; Is in
	["notin"]  = "∉", -- &#8713; Not in
	["ni"]     = "∋", -- &#8715; Ni
	["prod"]   = "∏", -- &#8719; Product
	["sum"]    = "∑", -- &#8721; Sum
	["minus"]  = "−", -- &#8722; Minus
	["lowast"] = "∗", -- &#8727; Asterisk (Lowast)
	["radic"]  = "√", -- &#8730; Square root
	["prop"]   = "∝", -- &#8733; Proportional to
	["infin"]  = "∞", -- &#8734; Infinity
	["ang"]    = "∠", -- &#8736; Angle
	["and"]    = "∧", -- &#8743; And
	["or"]     = "∨", -- &#8744; Or
	["cap"]    = "∩", -- &#8745; Cap
	["cup"]    = "∪", -- &#8746; Cup
	["int"]    = "∫", -- &#8747; Integral
	["there4"] = "∴", -- &#8756; Therefore
	["sim"]    = "∼", -- &#8764; Similar to
	["cong"]   = "≅", -- &#8773; Congurent to
	["asymp"]  = "≈", -- &#8776; Almost equal
	["ne"]     = "≠", -- &#8800; Not equal
	["equiv"]  = "≡", -- &#8801; Equivalent
	["le"]     = "≤", -- &#8804; Less or equal
	["ge"]     = "≥", -- &#8805; Greater or equal
	["sub"]    = "⊂", -- &#8834; Subset of
	["sup"]    = "⊃", -- &#8835; Superset of
	["nsub"]   = "⊄", -- &#8836; Not subset of
	["sube"]   = "⊆", -- &#8838; Subset or equal
	["supe"]   = "⊇", -- &#8839; Superset or equal
	["oplus"]  = "⊕", -- &#8853; Circled plus
	["otimes"] = "⊗", -- &#8855; Circled times
	["perp"]   = "⊥", -- &#8869; Perpendicular
	["sdot"]   = "⋅", -- &#8901; Dot operator

	-- Greek Letters
	["Alpha"]    = "Α", -- &#913; Alpha
	["Beta"]     = "Β", -- &#914; Beta
	["Gamma"]    = "Γ", -- &#915; Gamma
	["Delta"]    = "Δ", -- &#916; Delta
	["Epsilon"]  = "Ε", -- &#917; Epsilon
	["Zeta"]     = "Ζ", -- &#918; Zeta
	["Eta"]      = "Η", -- &#919; Eta
	["Theta"]    = "Θ", -- &#920; Theta
	["Iota"]     = "Ι", -- &#921; Iota
	["Kappa"]    = "Κ", -- &#922; Kappa
	["Lambda"]   = "Λ", -- &#923; Lambda
	["Mu"]       = "Μ", -- &#924; Mu
	["Nu"]       = "Ν", -- &#925; Nu
	["Xi"]       = "Ξ", -- &#926; Xi
	["Omicron"]  = "Ο", -- &#927; Omicron
	["Pi"]       = "Π", -- &#928; Pi
	["Rho"]      = "Ρ", -- &#929; Rho
	["Sigma"]    = "Σ", -- &#931; Sigma
	["Tau"]      = "Τ", -- &#932; Tau
	["Upsilon"]  = "Υ", -- &#933; Upsilon
	["Phi"]      = "Φ", -- &#934; Phi
	["Chi"]      = "Χ", -- &#935; Chi
	["Psi"]      = "Ψ", -- &#936; Psi
	["Omega"]    = "Ω", -- &#937; Omega
	["alpha"]    = "α", -- &#945; alpha
	["beta"]     = "β", -- &#946; beta
	["gamma"]    = "γ", -- &#947; gamma
	["delta"]    = "δ", -- &#948; delta
	["epsilon"]  = "ε", -- &#949; epsilon
	["zeta"]     = "ζ", -- &#950; zeta
	["eta"]      = "η", -- &#951; eta
	["theta"]    = "θ", -- &#952; theta
	["iota"]     = "ι", -- &#953; iota
	["kappa"]    = "κ", -- &#954; kappa
	["lambda"]   = "λ", -- &#955; lambda
	["mu"]       = "μ", -- &#956; mu
	["nu"]       = "ν", -- &#957; nu
	["xi"]       = "ξ", -- &#958; xi
	["omicron"]  = "ο", -- &#959; omicron
	["pi"]       = "π", -- &#960; pi
	["rho"]      = "ρ", -- &#961; rho
	["sigmaf"]   = "ς", -- &#962; sigmaf
	["sigma"]    = "σ", -- &#963; sigma
	["tau"]      = "τ", -- &#964; tau
	["upsilon"]  = "υ", -- &#965; upsilon
	["phi"]      = "φ", -- &#966; phi
	["chi"]      = "χ", -- &#967; chi
	["psi"]      = "ψ", -- &#968; psi
	["omega"]    = "ω", -- &#969; omega
	["thetasym"] = "ϑ", -- &#977; Theta symbol
	["upsih"]    = "ϒ", -- &#978; Upsilon symbol
	["piv"]      = "ϖ", -- &#982; Pi symbol

	-- Miscellaneous HTML entities
	["OElig"]  = "Œ", -- &#338; Uppercase ligature OE
	["oelig"]  = "œ", -- &#339; Lowercase ligature OE
	["Scaron"] = "Š", -- &#352; Uppercase S with caron
	["scaron"] = "š", -- &#353; Lowercase S with caron
	["Yuml"]   = "Ÿ", -- &#376; Capital Y with diaeres
	["fnof"]   = "ƒ", -- &#402; Lowercase with hook
	["circ"]   = "ˆ", -- &#710; Circumflex accent
	["tilde"]  = "˜", -- &#732; Tilde
	["ensp"]   = " ", -- &#8194; En space
	["emsp"]   = " ", -- &#8195; Em space
	["thinsp"] = " ", -- &#8201; Thin space
	["zwnj"]   = "‌", -- &#8204; Zero width non-joiner
	["zwj"]    = "‍", -- &#8205; Zero width joiner
	["lrm"]    = "‎", -- &#8206; Left-to-right mark
	["rlm"]    = "‏", -- &#8207; Right-to-left mark
	["ndash"]  = "–", -- &#8211; En dash
	["mdash"]  = "—", -- &#8212; Em dash
	["lsquo"]  = "‘", -- &#8216; Left single quotation mark
	["rsquo"]  = "’", -- &#8217; Right single quotation mark
	["sbquo"]  = "‚", -- &#8218; Single low-9 quotation mark
	["ldquo"]  = "“", -- &#8220; Left double quotation mark
	["rdquo"]  = "”", -- &#8221; Right double quotation mark
	["bdquo"]  = "„", -- &#8222; Double low-9 quotation mark
	["dagger"] = "†", -- &#8224; Dagger
	["Dagger"] = "‡", -- &#8225; Double dagger
	["bull"]   = "•", -- &#8226; Bullet
	["hellip"] = "…", -- &#8230; Horizontal ellipsis
	["permil"] = "‰", -- &#8240; Per mille
	["prime"]  = "′", -- &#8242; Minutes (Degrees)
	["Prime"]  = "″", -- &#8243; Seconds (Degrees)
	["lsaquo"] = "‹", -- &#8249; Single left angle quotation
	["rsaquo"] = "›", -- &#8250; Single right angle quotation
	["oline"]  = "‾", -- &#8254; Overline
	["euro"]   = "€", -- &#8364; Euro
	["trade"]  = "™", -- &#8482; Trademark
	["larr"]   = "←", -- &#8592; Left arrow
	["uarr"]   = "↑", -- &#8593; Up arrow
	["rarr"]   = "→", -- &#8594; Right arrow
	["darr"]   = "↓", -- &#8595; Down arrow
	["harr"]   = "↔", -- &#8596; Left right arrow
	["crarr"]  = "↵", -- &#8629; Carriage return arrow
	["lceil"]  = "⌈", -- &#8968; Left ceiling
	["rceil"]  = "⌉", -- &#8969; Right ceiling
	["lfloor"] = "⌊", -- &#8970; Left floor
	["rfloor"] = "⌋", -- &#8971; Right floor
	["loz"]    = "◊", -- &#9674; Lozenge
	["spades"] = "♠", -- &#9824; Spade
	["clubs"]  = "♣", -- &#9827; Club
	["hearts"] = "♥", -- &#9829; Heart
	["diams"]  = "♦", -- &#9830; Diamond
}
